FROM oven/bun:1


WORKDIR /usr/src/app

# COPY package.json ./package.json
COPY  ./packages ./packages
COPY  ./bun.lock ./bun.lock

COPY  ./package.json ./package.json
COPY  ./turbo.json ./turbo.json

COPY ./apps/http-backend ./apps/http-backend


RUN bun install
RUN bun run db:generate

EXPOSE 8080

CMD [ "bun","run" ,"start:http-backend"]


#docker build  --build-arg DATABASE_URL="green" -t todo-app-frontend -f ./docker/Dockerfile.frontend .
